### ISSUE TITLE
Call to undefined function Illuminate\Support\enum_value()

### ISSUE THREAD

**Issue by Frooplet** [kawax/laravel-bluesky#17]
I installed the package via composer and tried the basic example to fetch a feed.

```
$response = Bluesky::getAuthorFeed(actor: 'bsky.app');
$ret = $response->collect('feed');
```

I run immediately into an error: "Call to undefined function Illuminate\Support\enum_value()".
Any idea what might be causing this problem?

PHP 8.2.4 — Laravel 11.22.0

**Comment by kawax** [comment]
You should always use the latest version of Laravel.

`enum_value()` was added in v11.28.0.
Please run `composer update`.
