### ISSUE TITLE
OAuth scope and local development

### ISSUE THREAD

**Issue by benjamindavid** [kawax/laravel-bluesky#9]
I wondering why on `atproto` scope is available for local development? I haven't found any docs mentioning this and I'm wondering how to make other scopes like `transition:generic` or `transition:chat.bsky` work locally.

https://github.com/kawax/laravel-bluesky/blob/main/src/Socialite/Concerns/WithPAR.php#L44

Thanks!

**Comment by kawax** [comment]
Only the atproto scope is available locally. Probably to prevent spam.

I couldn't post even if I set other scopes. I've already tried that.

https://atproto.com/ja/specs/oauth

**Comment by kawax** [comment]
App password allows posting locally.

**Comment by benjamindavid** [comment]
Thanks a lot for your response and the great lib @kawax 🙏
